force-app/main/default/objects/Account/fields/CNAE__c.field-meta.xml
<CustomField>
    <fullName>CNAE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CNAE</label>
    <referenceTo>CNAE__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CNAE__c/CNAE__c.object-meta.xml
<CustomObject>
    <label>CNAE</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNAES</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <description>TotalAmount</description>
    <label>TotalAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ContractTriggerTest.cls
@isTest
public class ContractTriggerTest {
    
    @isTest
    public static void shouldUpdateAccountWithTotalActiveContracts () {
        
        Map<String, SObject> records = AccountFixtureFactory.createIntegratedScenario ();

        Account account = (Account) records.get('default-account');

        Cnae__c cnae = (Cnae__c) records.get('cnae');

        Account otherAccount = AccountFixtureFactory.createAccount('Teste Other', '12321312', cnae);

        List<Contract> contracts = new List<Contract>();

        Decimal expectedTotal = 0;

        for ( Integer i = 0; i < 10; i++) {

            if ( Math.mod (i, 3) ==  0 ) {
                Contract contract = ContractFixtureFactory.newContract('231423432', account);
                contract.TotalAmount__c = 10;                
                contracts.add(contract);

                expectedTotal += contract.TotalAmount__c;
            }

        }



        Test.startTest();
        
        insert contracts;
        
        Test.stopTest();

        Account storedAccount = [SELECT Id, TotalActiveContracts__c 
                                  FROM Account WHERE Id = :account.Id ];


        Assert.areEqual(expectedTotal, storedAccount.TotalActiveContracts__c);


    }

}