force-app/main/default/objects/Account/fields/CNAE__c.field-meta.xml
<CustomField>
    <fullName>CNAE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CNAE</label>
    <referenceTo>CNAE__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CNAE__c/CNAE__c.object-meta.xml
<CustomObject>
    <label>CNAE</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNAES</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/account/AccountFixtureFactory.cls
@isTest
public class AccountFixtureFactory {

    public static Account createAccount (String name, String document, CNAE__c cnae) {
        return save( newAccount(name, document, cnae) );
    }
 
    public static Account newAccount (String name, String document, CNAE__c cnae) {

        Account account = newAccount (name,document);
        account.CNAE__c = cnae.Id;
        return account;

    }

    public static Account createAccount (String name, String document, String postalCode ) {
        return save( newAccount(name, document,postalCode) );
    }

    public static Account newAccount (String name, String document, String postalCode ) {
        
        Account account = newAccount (name,document);
        account.BillingPostalCode = postalCode;
        return account;
        
    }
    
    public static Account newAccount (String name, String document) {
        return new Account (Name = name, 
                        CpfCnpj__c = document,
                        BillingStreet =  'Rua Xyz');
    }

    public static Account save (Account account) {
        upsert account;
        return account;        
    }


    public static Map<String, SObject> createIntegratedScenario () {

        Map<String, SObject> records = new Map<String, SObject>();

        CNAE__c cnae = CnaeFixtureFactory.createCnae('1234242323');

        records.put ('cnae', cnae);

        Account account = AccountFixtureFactory.createAccount('jhsdfjhsdj'
                                                            , '123211323'
                                                            , cnae);
        records.put ('default-account', account);

        return records;
    }

}