force-app/main/default/objects/Account/fields/CNAE__c.field-meta.xml
<CustomField>
    <fullName>CNAE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CNAE</label>
    <referenceTo>CNAE__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CNAE__c/CNAE__c.object-meta.xml
<CustomObject>
    <label>CNAE</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNAES</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/account/AccountTriggerTest.cls
@isTest
public class AccountTriggerTest {

    @isTest
    public static void shouldBlockToInsertAccountWithWrongDocument () {

        CNAE__c cnae = CnaeFixtureFactory.createCnae('123213');

        Account account = AccountFixtureFactory.newAccount('Name', '123123131X', cnae);

        Test.startTest();

        try {

            insert account;

            Assert.fail('DmlException Expected');

        } catch (DmlException e) {
                        
            Assert.areEqual( 'Documento Inválido' , e.getDmlMessage(0));

        } 
        
        Test.stopTest();

    }

    @isTest
    public static void shouldBlockToChangeAccountWithWrongDocument () {

        Map<String,SObject> records = AccountFixtureFactory.createIntegratedScenario();

        Account account = (Account) records.get('default-account');

        Test.startTest();

        try {

            account.CpfCnpj__c = '0238723872S';

            update account;

            Assert.fail('DmlException Expected');

        } catch (DmlException e) {
                        
            Assert.areEqual( 'Documento Inválido' , e.getDmlMessage(0));

        } 
        
        Test.stopTest();

    }

}