force-app/main/default/objects/Account/fields/CNAE__c.field-meta.xml
<CustomField>
    <fullName>CNAE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CNAE</label>
    <referenceTo>CNAE__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CNAE__c/CNAE__c.object-meta.xml
<CustomObject>
    <label>CNAE</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNAES</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CNAE__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/account/AccountRepositoryTest.cls
@isTest
public class AccountRepositoryTest {

    @isTest
    public static void shouldCreateAccountWithBillingStreet() {

        // crio registros dentro da plataforma 
        // para q meu teste possa ser executado

        // --------------- preparacao - setup

        CNAE__c cnae = new CNAE__c( Code__c = '12321'
                                   , Description__c = '12312' );

        insert cnae;

        List<Account> databaseAccounts = [SELECT Id FROM Account];

        Assert.isTrue( databaseAccounts.isEmpty() );

        List<Account> accounts = new List<Account> {
            new Account (Name = 'Xyz', 
                        CpfCnpj__c = '12345678901234',
                        BillingStreet = 'Rua Xyz' ,
                        CNAE__c = cnae.Id )
        };

        // ------------------

        Test.startTest();

        AccountRepository repository = new AccountRepository();

        List<Account> storedAccounts = repository.save(accounts);

        System.debug( Limits.getDmlRows() );
        System.debug( Limits.getQueryRows() );

        Test.stopTest();

        Assert.areEqual(1, storedAccounts.size() );
        Assert.isNotNull( storedAccounts.get(0).Id, 'O Id de Account deve ser informado' );
        Assert.isNotNull( storedAccounts.get(0).BillingStreet, 'Deve ser informado o BillingStreet' );

    }
    
}