force-app/main/default/objects/CNAE__c/CNAE__c.object-meta.xml
<CustomObject>
    <label>CNAE</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CNAES</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CNAE__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/account/CnaeFixtureFactory.cls
@isTest
public class CnaeFixtureFactory {
    
    public static CNAE__c createCnae (String code) {
        return save( newCnae(code) );
    }

    public static CNAE__c newCnae (String code) {
        return new CNAE__c (Code__c = code, 
                        Description__c = 'Teste CNae' );
    }

    public static CNAE__c save (CNAE__c cnae) {
        upsert cnae;
        return cnae;        
    }



}